# Generated by Django 3.2.21 on 2023-09-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='length',
            new_name='minutes',
        ),
    ]
